package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"net/http"
	"sync"

	"google.golang.org/protobuf/proto"

	// Import the generated Protobuf Go file
	"testClient/matchmaking/party"
)

func main() {

	partyRequests := []*party.Players{
		{
			Player1Puuid:       "Xo7QpJdK-2YgVzLtRAEm6c0f5_WxA8PqBN3yL9vMGbJhFzsTUKCdN4QoS1pZGXWA",
			Player1RiotName:    "Spica",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "18",
			Player1Role:        "Bottom",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723LJ2",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "JvU9pQmG-0YxBTfNhLKCA3Ro2WzXlJqM7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdT3",
			Player1RiotName:    "BobbyB",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "19",
			Player1Role:        "Top",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL7239D2",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9B",
			Player1RiotName:    "Haidder",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "20",
			Player1Role:        "Top",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723MK1",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YB",
			Player1RiotName:    "Mingle",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "21",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723VQ7",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybNX",
			Player1RiotName:    "Dingle",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "21",
			Player1Role:        "Jungle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723K8L",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "2YgVzLtRAEm6c0f5_WxA8PqBN3l9vMGbJhFzsTUKCdN4QoS1pZGXWJvU9pQmG0x",
			Player1RiotName:    "Karar",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "22",
			Player1Role:        "Support",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723H4M",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3o",
			Player1RiotName:    "Anghel",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "22",
			Player1Role:        "Jungle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723FQ9",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "RAEm6c0f5_WxA8PqBN3yL9vMGbJhFzsTUKCdN4QoS1pZGXWJvU9pQmG0YxBTfNh7",
			Player1RiotName:    "Zizzy",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "18",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723D1Y",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "WJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4o",
			Player1RiotName:    "Fruity",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "20",
			Player1Role:        "Top",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723UQ3",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "F6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNhLP",
			Player1RiotName:    "Mathmood",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "19",
			Player1Role:        "Support",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723J7L",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "M7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0",
			Player1RiotName:    "Zeus",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "23",
			Player1Role:        "Bottom",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723I9N",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "N4QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybXoEWsK1L9RBpCdTJ3KCA3W",
			Player1RiotName:    "Apollo",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "22",
			Player1Role:        "Support",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723Q6F",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNhL7Pg",
			Player1RiotName:    "Butts",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "42",
			Player1Role:        "Jungle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723U8F",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "BTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvUp",
			Player1RiotName:    "Guts",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "39",
			Player1Role:        "Top",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723V6Y",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCT",
			Player1RiotName:    "Nuts",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "38",
			Player1Role:        "Bottom",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723N1Z",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "1dF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNh7",
			Player1RiotName:    "Gaze",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "38",
			Player1Role:        "Support",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723V5X",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3o",
			Player1RiotName:    "Athena",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "39",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723L7Y",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "WJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4o",
			Player1RiotName:    "Hera",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "40",
			Player1Role:        "Jungle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723Q2K",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "RAEm6c0f5_WxA8PqBN3yL9vMGbJhFzsTUKCdN4QoS1pZGXWJvU9pQmG0YxBTfNh7",
			Player1RiotName:    "Achiles",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "41",
			Player1Role:        "Top",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723D6W",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEW-",
			Player1RiotName:    "Hercules",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "30",
			Player1Role:        "Bottom",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723L3T",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4X",
			Player1RiotName:    "Dionysus",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "38",
			Player1Role:        "Support",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723N4C",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "JvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1",
			Player1RiotName:    "Artemis",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "39",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723M9Y",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "M7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0Yx",
			Player1RiotName:    "Hermes",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "40",
			Player1Role:        "Jungle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723X0B",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "BTfNhL7P5g8ZVdF6tAybN4QoS1pZGXWJvU9p-GFDGSDFGD5623654GDFGHB5234BDB",
			Player1RiotName:    "Hephaestus",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "42",
			Player1Role:        "Top",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723S6Q",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "2YgVzLtRAEm6c0f5_WxA8PqBN3yL9vMGbJhFzsTUKCdN4QoS1pZGXWJvU9pQmG0Yx",
			Player1RiotName:    "Zephyrus",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "43",
			Player1Role:        "Bottom",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723Y5B",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6",
			Player1RiotName:    "Ares",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "23",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723B8F",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3Xo",
			Player1RiotName:    "Poseidon",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "20",
			Player1Role:        "Jungle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723B1M",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "BTfNhL7P5g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9p",
			Player1RiotName:    "Hades",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "20",
			Player1Role:        "Bottom",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723R4M",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "yL9vMGbJhFzsTUKCdN4QoS1pZGXWJvU9pQmG0YxBTfNhL7P5g8ZVdF6tAybN4XoW",
			Player1RiotName:    "Shmekkles",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "40",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723G9W",
			TeamCount:          "1",
			QueueType:          420,
		},
		{
			Player1Puuid:       "g8ZVdF6tAybN4XoEWsK1L9RBpCdTJ3KCA3XoEWs-N4QoS1pZGXWJvU9pQmG0YxBf",
			Player1RiotName:    "NMOAF",
			Player1RiotTagLine: "NA1",
			Player1Rank:        "41",
			Player1Role:        "Middle",
			Player2Puuid:       "",
			Player2RiotName:    "",
			Player2RiotTagLine: "",
			Player2Rank:        "",
			Player2Role:        "",
			PartyId:            "PARTY_5JKL723D8X",
			TeamCount:          "1",
			QueueType:          420,
		},
	}

	// fmt.Printf("PartyRequest: %+v\n", partyRequest)

	var wg sync.WaitGroup

	// targetUser := 20
	// for i := targetUser; i < (targetUser + 2); i++ {
	for i := 0; i < len(partyRequests); i++ {
		wg.Add(1)
		go func(pr *party.Players) {
			defer wg.Done()

			data, err := proto.Marshal(pr)
			if err != nil {
				log.Printf("Failed to marshal Protobuf: %v", err)
				return
			}

			resp, err := http.Post("http://localhost:8080/queueUp", "application/x-protobuf", bytes.NewReader(data))
			if err != nil {
				log.Printf("Failed to send request: %v", err)
				return
			}
			responseBody, _ := io.ReadAll(resp.Body)
			resp.Body.Close()
			fmt.Printf("%s", responseBody)

			matchmakingResponse, err := http.Post("http://localhost:8080/matchmaking", "application/x-protobuf", bytes.NewReader(data))
			if err != nil {
				log.Printf("Failed to send matchmaking request: %v", err)
				return
			}
			parsedResponse, _ := io.ReadAll(matchmakingResponse.Body)
			matchmakingResponse.Body.Close()
			fmt.Printf("%s", parsedResponse)
		}(partyRequests[i])
	}

	wg.Wait()

}
