syntax = "proto3";

package party;

// The go_package option specifies the import path for the generated Go code.
option go_package = "./party";

message Participant {
    string riotName = 1;
    string riotTagLine = 2;
    string rank = 3;
    string role = 4;
    string puuid = 5;
    string partyId = 6;
    string teamCount = 7;
    int32 queueType = 8;
}

message PartyRequest {
    string partyId = 1;
    string teamCount = 2;
    int32 queueType = 3;
    repeated Participant participants = 4;  // List of participants
}